### ISSUE TITLE
Issue with DFS unreachable case

### ISSUE THREAD

**Issue by SUSHANT12PRABHU** [hwaseem04/AI-Algorithm-Visualisation#2]
Great project but you may want to relook at this edge case of saying Solved which is incorrect for the attached input.
<img width="1058" alt="Screenshot 2022-12-10 at 9 00 46 PM" src="https://user-images.githubusercontent.com/23032355/206883033-4547e6f2-db22-4029-930f-fee29fe65899.png">

**Comment by hwaseem04** [comment]
This issue is prevalent in most of the algorithms. I have refactored dfs & bfs in my new branch. Will close this issue once I refactored all the algorithms and merge it to my main branch. Thanks for raising this issue : )
